#!/bin/bash
# SessionStart hook for Claude Code on the web: make a fresh session immediately
# able to run dev / test / typecheck without manual setup.
set -euo pipefail

# Only run in remote (web) sessions; local devs manage their own environment.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

cd "$CLAUDE_PROJECT_DIR"

# ── Stale-snapshot self-heal ─────────────────────────────────────────────────
# The remote container is sometimes recycled mid-session and restored from an
# OLD workspace snapshot, silently rewinding HEAD (and the working tree) to a
# commit that predates work already pushed to origin/main. Anything uncommitted
# was lost in the recycle itself, so when we detect HEAD strictly BEHIND
# origin/main on the main branch, hard-resetting to origin/main discards only
# stale-snapshot junk and restores the real state. (A diverged/ahead HEAD is
# left alone — that's genuine local work, not a stale snapshot.)
if git fetch origin main --quiet 2>/dev/null; then
  BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '')
  if [ "$BRANCH" = "main" ]; then
    LOCAL=$(git rev-parse HEAD)
    REMOTE=$(git rev-parse origin/main)
    if [ "$LOCAL" != "$REMOTE" ] && git merge-base --is-ancestor "$LOCAL" origin/main; then
      git reset --hard origin/main --quiet
      echo "git: stale snapshot detected — reset to origin/main ($(git rev-parse --short HEAD))"
    fi
  fi
fi

# Ensure pnpm is available (Corepack ships with Node; packageManager is pinned).
if ! command -v pnpm >/dev/null 2>&1; then
  corepack enable >/dev/null 2>&1 || true
fi

# Install dependencies from the committed lockfile (idempotent + reproducible).
if pnpm install --frozen-lockfile > /tmp/pnpm-install.log 2>&1; then
  echo "deps: pnpm install OK"
else
  echo "deps: pnpm install FAILED"; tail -30 /tmp/pnpm-install.log; exit 1
fi

# next-env.d.ts is gitignored and normally generated by `next build`. Create it
# up front so `pnpm typecheck` (tsc) resolves image/static imports in a fresh
# checkout without needing a full build first.
if [ ! -f next-env.d.ts ]; then
  printf '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// NOTE: This file should not be edited\n// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.\n' > next-env.d.ts
  echo "types: created next-env.d.ts"
fi

echo "session-start hook complete"
