import 'server-only'
import Anthropic from '@anthropic-ai/sdk'
import { z } from 'zod'
import type { InboxPatientContext } from '@/lib/types/patient-context'
import { EMAIL_CATEGORIES, EMAIL_INTENTS, type EmailCategory, type EmailIntent } from '@/lib/db/schema/email'

/**
 * AI-mailbox: Haiku for cheap classification on every incoming email,
 * Sonnet for higher-quality drafted replies that fold in patient context.
 * Both functions are best-effort — they swallow their own errors and
 * return null so the calling path (ingest, UI) never blocks on AI
 * availability.
 */

function getClient(): Anthropic | null {
  // Lazy-construct so the module can be imported during `next build` even
  // when the env var isn't set (e.g. preview deploys without the key).
  if (!process.env.ANTHROPIC_API_KEY) return null
  return new Anthropic()
}

// ============================================================
// Classification (Haiku 4.5 + structured output)
// ============================================================

const ClassificationSchema = z.object({
  category: z.enum(EMAIL_CATEGORIES),
  intent: z.enum(EMAIL_INTENTS),
})

export type EmailClassification = z.infer<typeof ClassificationSchema>

const CLASSIFY_SYSTEM = `You triage incoming emails for a dental clinic's front-desk inbox. For each email you assign TWO labels in one shot: a category (which inbox tab) and an intent (what it's about).

CATEGORY decides which tab the email lands in:

- "primary": A real person wrote this email personally to the clinic and the staff likely needs to read and respond. Patients asking about appointments, vendors with an actual question, partners following up, billing escalations from a human, etc. Even cold-outreach from a real human salesperson trying to start a conversation counts as primary — what matters is "human wrote this directly, expects a reply." A patient reaching out for the first time IS primary; do not require them to already be in our records.

- "updates": Automated or transactional content from a service the clinic uses. Receipts, payment confirmations, security alerts, password resets, calendar invites generated by software, account notifications, system status, software release notes, signed-document notifications, file-share notifications. Sent by a machine, useful to skim, doesn't need a reply.

- "promotions": Marketing, newsletters, sales pitches, "20% off this week", product announcements, vendor cold-blast emails, conference invitations, generic mass mailings. Anything sent to many recipients to push a product/event/content. List-Unsubscribe footers are a strong tell.

- "spam": Suspicious, phishing, scam, obviously-fake invoices, sextortion, lottery wins, malware delivery attempts. Use sparingly — only when you're confident it's malicious. Gmail filters most spam before it reaches us.

INTENT applies primarily to "primary" emails (for other categories use "other"). The buckets:

- "booking": Schedule, reschedule, confirm, or cancel an appointment
- "insurance": Coverage questions, claims, in-network status, eligibility
- "billing": Bills, payments, statements, invoices, account balance
- "records": Requests for x-rays, charts, prescriptions, referrals, records transfer
- "follow_up": General patient inquiry that needs a response and doesn't fit above
- "marketing": Use ONLY when category is "promotions"
- "other": Anything else

Be opinionated about category — when in doubt between primary and promotions, ask: "Did a specific human compose this just for us, or is it the same email sent to thousands of recipients?" The latter is promotions.`

interface ClassifyInput {
  fromEmail: string
  fromName: string | null
  subject: string | null
  bodyText: string | null
  bodyHtml: string | null
  snippet: string | null
}

function buildClassifyUserPrompt(args: ClassifyInput): string {
  // Prefer plain text. If only HTML, take first 1500 chars (the model can
  // read the tag soup well enough to triage). Truncation keeps latency
  // tight; the first ~1500 chars are nearly always sufficient.
  let body = (args.bodyText ?? '').trim()
  if (!body && args.bodyHtml) body = args.bodyHtml.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()
  if (!body) body = args.snippet ?? ''
  body = body.slice(0, 1500)

  const fromLabel = args.fromName ? `${args.fromName} <${args.fromEmail}>` : args.fromEmail
  return `From: ${fromLabel}
Subject: ${args.subject ?? '(no subject)'}

${body}`
}

export async function classifyMessage(args: ClassifyInput): Promise<EmailClassification | null> {
  const client = getClient()
  if (!client) return null
  try {
    const response = await client.messages.parse({
      model: 'claude-haiku-4-5',
      max_tokens: 64,
      system: CLASSIFY_SYSTEM,
      messages: [{ role: 'user', content: buildClassifyUserPrompt(args) }],
      output_config: {
        format: {
          type: 'json_schema',
          name: 'email_classification',
          schema: {
            type: 'object',
            properties: {
              category: { type: 'string', enum: EMAIL_CATEGORIES as unknown as string[] },
              intent: { type: 'string', enum: EMAIL_INTENTS as unknown as string[] },
            },
            required: ['category', 'intent'],
            additionalProperties: false,
          },
        },
      },
    })
    const parsed = response.parsed_output
    if (!parsed) return null
    return ClassificationSchema.parse(parsed)
  } catch (err) {
    console.warn('[ai] classifyMessage failed', err)
    return null
  }
}

// ============================================================
// Reply drafting (Sonnet 4.6 + adaptive thinking)
// ============================================================

const REPLY_SYSTEM = `You draft reply emails on behalf of a dental clinic's front-desk admin. Your output goes directly into the admin's reply textarea; they review and may edit before sending.

Tone: warm, professional, concise. Address the writer by first name when known. Match the formality of the incoming email — casual gets casual, formal gets formal.

Output rules:
- Plain text only — no markdown, no bullet lists unless the original was a list of questions to answer
- Two to three short paragraphs maximum
- Start with a one-line greeting (e.g. "Hi Lisa,")
- End with a clear next step or question, never "Looking forward to hearing from you"
- Do NOT add a signature, sign-off line ("Best", "Thanks", etc.), or the staff member's name — they add their own

Patient context handling:
- If a patient record is provided, weave in genuinely relevant details naturally — e.g. "I see you have a cleaning scheduled for May 21st" or "I noticed it's been a while since your last visit"
- Don't recite all the fields verbatim; only mention what the original email asks about or what the patient would expect us to know

Constraints — defer to staff for anything you can't verify:
- Do NOT commit to specific appointment times unless the original email proposes one and patient_context confirms availability
- Do NOT quote prices, copays, or fees
- Do NOT promise insurance coverage decisions
- When in doubt, offer to have a staff member follow up`

interface DraftReplyInput {
  patientContext: InboxPatientContext | null
  originalSubject: string | null
  originalBody: string
  fromName: string | null
  fromEmail: string
}

export async function draftReply(args: DraftReplyInput): Promise<string | null> {
  const client = getClient()
  if (!client) return null

  const ctx = args.patientContext
  const contextBlock = ctx
    ? `<patient_record>
name: ${ctx.patient.firstName} ${ctx.patient.lastName}
${ctx.patient.dateOfBirth ? `date_of_birth: ${ctx.patient.dateOfBirth}\n` : ''}${ctx.patient.phone ? `phone: ${ctx.patient.phone}\n` : ''}${ctx.patient.insuranceProvider ? `insurance: ${ctx.patient.insuranceProvider}\n` : ''}total_visits: ${ctx.appointmentCount}
${ctx.nextAppointment ? `next_appointment: ${ctx.nextAppointment.startTime.toISOString()} (${ctx.nextAppointment.type}, ${ctx.nextAppointment.status})` : 'next_appointment: none scheduled'}
${ctx.lastAppointment && new Date(ctx.lastAppointment.startTime) < new Date() ? `last_visit: ${ctx.lastAppointment.startTime.toISOString()} (${ctx.lastAppointment.type})` : 'last_visit: none on record'}
${ctx.patient.notes ? `notes: ${ctx.patient.notes}` : ''}
</patient_record>`
    : '<patient_record>This sender is NOT in our patient records.</patient_record>'

  const userText = `${contextBlock}

<incoming_email>
From: ${args.fromName ? `${args.fromName} <${args.fromEmail}>` : args.fromEmail}
Subject: ${args.originalSubject ?? '(no subject)'}

${args.originalBody.slice(0, 6000)}
</incoming_email>

Draft a reply now. Output only the email body — no preamble, no explanation.`

  try {
    // Stream internally to avoid SDK HTTP timeouts on slow generations;
    // collect into a single string before returning. Adaptive thinking
    // lets the model dial up reasoning when patient context makes the
    // reply non-trivial.
    const stream = client.messages.stream({
      model: 'claude-sonnet-4-6',
      max_tokens: 4000,
      thinking: { type: 'adaptive' },
      system: REPLY_SYSTEM,
      messages: [{ role: 'user', content: userText }],
    })
    const final = await stream.finalMessage()
    const block = final.content.find((b) => b.type === 'text')
    if (block && block.type === 'text') return block.text.trim()
    return null
  } catch (err) {
    console.warn('[ai] draftReply failed', err)
    return null
  }
}

// ============================================================
// Batched classification (parallel with bounded concurrency)
// ============================================================

/**
 * Classify a batch of messages in parallel. Bounded concurrency so a
 * 200-message backfill doesn't burst the Haiku rate limit. Returns a map
 * of messageId → { category, intent } for ones we successfully classified.
 */
export async function classifyBatch(
  messages: Array<ClassifyInput & { id: string }>,
  concurrency = 8,
): Promise<Map<string, EmailClassification>> {
  const result = new Map<string, EmailClassification>()
  let cursor = 0
  async function worker() {
    while (cursor < messages.length) {
      const i = cursor++
      const msg = messages[i]
      const classification = await classifyMessage(msg)
      if (classification) result.set(msg.id, classification)
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, messages.length) }, worker))
  return result
}

// Backward-compat wrapper (older callers expected just an intent).
export async function classifyIntent(args: ClassifyInput): Promise<EmailIntent | null> {
  const result = await classifyMessage(args)
  return result?.intent ?? null
}
