import 'server-only'
import { runClaudeText, aiConfigured } from '@/lib/ai'
import { z } from 'zod'
import type { InboxPatientContext } from '@/lib/types/patient-context'
import { EMAIL_CATEGORIES, EMAIL_INTENTS, type EmailCategory, type EmailIntent } from '@/lib/db/schema/email'

/**
 * AI-mailbox: Haiku for cheap classification on every incoming email,
 * Sonnet for higher-quality drafted replies that fold in patient context.
 * Both functions are best-effort — they swallow their own errors and
 * return null so the calling path (ingest, UI) never blocks on AI
 * availability.
 */

// ============================================================
// Classification (Haiku 4.5 + structured output)
// ============================================================

const ClassificationSchema = z.object({
  category: z.enum(EMAIL_CATEGORIES),
  intent: z.enum(EMAIL_INTENTS),
})

export type EmailClassification = z.infer<typeof ClassificationSchema>

const CLASSIFY_SYSTEM = `You triage incoming emails for a dental clinic's front-desk inbox. For each email you assign TWO labels in one shot: a category (which inbox tab) and an intent (what it's about).

CATEGORY decides which tab the email lands in:

- "primary": A real person wrote this email personally to the clinic and the staff likely needs to read and respond. Patients asking about appointments, vendors with an actual question, partners following up, billing escalations from a human, etc. Even cold-outreach from a real human salesperson trying to start a conversation counts as primary — what matters is "human wrote this directly, expects a reply." A patient reaching out for the first time IS primary; do not require them to already be in our records.

- "updates": Automated or transactional content from a service the clinic uses. Receipts, payment confirmations, security alerts, password resets, calendar invites generated by software, account notifications, system status, software release notes, signed-document notifications, file-share notifications, uptime/monitoring reports, support-ticket auto-replies. Sent by a machine, useful to skim, doesn't need a reply.

- "promotions": Marketing, newsletters, sales pitches, "20% off this week", product announcements, vendor cold-blast emails, conference invitations, generic mass mailings. Anything sent to many recipients to push a product/event/content. List-Unsubscribe footers are a strong tell. Many emails from companies like Bluevine, Calendly, Stripe-marketing, etc. are promotions if they're pushing features/products vs. transactional confirmations.

- "spam": ONLY messages that are clearly malicious — phishing attempting to steal credentials, scams (Nigerian prince, sextortion, lottery winnings), obviously-fake invoices, malware delivery. Gmail filters almost all of these before they reach us, so the bar here is very high. If a message mentions the word "spam" in its content (e.g. someone testing deliverability, asking about spam filters, discussing email marketing), that does NOT make it spam — judge by intent, not vocabulary. If you're not 100% certain a message is malicious, choose another category. When torn between spam and primary, always pick primary.

INTENT applies primarily to "primary" emails (for other categories use "other"). The buckets:

- "booking": Schedule, reschedule, confirm, or cancel an appointment
- "insurance": Coverage questions, claims, in-network status, eligibility
- "billing": Bills, payments, statements, invoices, account balance
- "records": Requests for x-rays, charts, prescriptions, referrals, records transfer
- "follow_up": General patient inquiry that needs a response and doesn't fit above
- "marketing": Use ONLY when category is "promotions"
- "other": Anything else

Be opinionated about category — when in doubt between primary and promotions, ask: "Did a specific human compose this just for us, or is it the same email sent to thousands of recipients?" The latter is promotions.

OUTPUT FORMAT — respond with ONLY a single JSON object, nothing else, no markdown fence, no preamble:
{"category": "...", "intent": "..."}`

interface ClassifyInput {
  fromEmail: string
  fromName: string | null
  subject: string | null
  bodyText: string | null
  bodyHtml: string | null
  snippet: string | null
}

function buildClassifyUserPrompt(args: ClassifyInput): string {
  // Prefer plain text. If only HTML, take first 1500 chars (the model can
  // read the tag soup well enough to triage). Truncation keeps latency
  // tight; the first ~1500 chars are nearly always sufficient.
  let body = (args.bodyText ?? '').trim()
  if (!body && args.bodyHtml) body = args.bodyHtml.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()
  if (!body) body = args.snippet ?? ''
  body = body.slice(0, 1500)

  const fromLabel = args.fromName ? `${args.fromName} <${args.fromEmail}>` : args.fromEmail
  return `From: ${fromLabel}
Subject: ${args.subject ?? '(no subject)'}

${body}`
}

export async function classifyMessage(args: ClassifyInput): Promise<EmailClassification | null> {
  if (!aiConfigured()) {
    console.warn('[ai.classify] AI driver not configured — skipping')
    return null
  }
  try {
    // Plain-text completion + JSON.parse turned out to be more reliable than
    // structured output, which occasionally produced empty parsed output with
    // no error. Haiku follows the "respond with only JSON" instruction well.
    const out = await runClaudeText({
      model: 'haiku',
      maxTokens: 64,
      system: CLASSIFY_SYSTEM,
      messages: [{ role: 'user', content: buildClassifyUserPrompt(args) }],
    })
    const raw = out ? out.trim() : ''
    if (!raw) {
      console.warn('[ai.classify] empty response from haiku')
      return null
    }
    // Tolerate occasional code-fence wrapping.
    const json = raw
      .replace(/^```(?:json)?\s*/i, '')
      .replace(/\s*```$/i, '')
      .trim()
    let parsed: unknown
    try {
      parsed = JSON.parse(json)
    } catch {
      console.warn('[ai.classify] non-JSON response:', raw.slice(0, 200))
      return null
    }
    const result = ClassificationSchema.safeParse(parsed)
    if (!result.success) {
      console.warn('[ai.classify] invalid shape:', JSON.stringify(parsed), result.error.message)
      return null
    }
    return result.data
  } catch (err) {
    console.warn('[ai.classify] request failed:', (err as Error).message)
    return null
  }
}

// ============================================================
// Reply drafting (Sonnet 4.6 + adaptive thinking)
// ============================================================

const REPLY_SYSTEM_CLINIC = `You draft reply emails on behalf of a dental clinic's front-desk admin. Your output goes directly into the admin's reply textarea; they review and may edit before sending.

Tone: warm, professional, concise. Address the writer by first name when known. Match the formality of the incoming email — casual gets casual, formal gets formal.

Output rules:
- Plain text only — no markdown, no bullet lists unless the original was a list of questions to answer
- Two to three short paragraphs maximum
- Start with a one-line greeting (e.g. "Hi Lisa,")
- End with a clear next step or question, never "Looking forward to hearing from you"
- Do NOT add a signature, sign-off line ("Best", "Thanks", etc.), or the staff member's name — they add their own

Patient context handling:
- If a patient record is provided, weave in genuinely relevant details naturally — e.g. "I see you have a cleaning scheduled for May 21st" or "I noticed it's been a while since your last visit"
- Don't recite all the fields verbatim; only mention what the original email asks about or what the patient would expect us to know

Constraints — defer to staff for anything you can't verify:
- Do NOT commit to specific appointment times unless the original email proposes one and patient_context confirms availability
- Do NOT quote prices, copays, or fees
- Do NOT promise insurance coverage decisions
- When in doubt, offer to have a staff member follow up`

const REPLY_SYSTEM_PLATFORM = `You draft reply emails on behalf of the owner of Dream Create, a B2B SaaS platform (DreamCRM) sold to dental clinics. The recipients you're replying to are typically clinic owners, prospects evaluating the product, or vendors / partners. Your output goes directly into the owner's reply textarea; they review and may edit before sending.

Tone: warm, founder-direct, concise. Address the writer by first name when known. Match the formality of the incoming email — casual gets casual, formal gets formal. You can sound human and personal — this is a small company writing to other small business owners.

Output rules:
- Plain text only — no markdown, no bullet lists unless the original was a list of questions to answer
- Two to three short paragraphs maximum
- Start with a one-line greeting (e.g. "Hi Sarah,")
- End with a clear next step or question, never "Looking forward to hearing from you"
- Do NOT add a signature, sign-off line ("Best", "Thanks", etc.), or the owner's name — they add their own

Client context handling:
- If a client record is provided, mention what's genuinely relevant (e.g. their name, that they're already on the platform) but don't recite fields the recipient would already know about themselves
- If the sender is not in records, treat them as new — offer to set up a call, share a demo link, answer questions

Constraints — defer to the owner for anything you can't verify:
- Do NOT commit to specific pricing or discounts
- Do NOT promise specific feature delivery dates or roadmap commitments
- Do NOT make legal or contractual commitments (refunds, SLAs, etc.)
- When in doubt, offer to follow up after checking with the owner`

interface DraftReplyInput {
  patientContext: InboxPatientContext | null
  originalSubject: string | null
  originalBody: string
  fromName: string | null
  fromEmail: string
  /**
   * Tenant type drives which system prompt to use. Platform-tenant replies
   * are drafted from the SaaS owner's POV; clinic-tenant replies from the
   * front-desk admin's POV. Defaults to clinic if not supplied (backward
   * compat with older callers).
   */
  tenantType?: 'platform' | 'clinic'
}

export async function draftReply(args: DraftReplyInput): Promise<string | null> {
  if (!aiConfigured()) return null

  const isPlatform = args.tenantType === 'platform'
  const ctx = args.patientContext
  const recordTag = isPlatform ? 'client_record' : 'patient_record'

  let contextBlock: string
  if (ctx) {
    if (isPlatform) {
      // Platform clients: only show fields that make sense for B2B context.
      // Skip DOB / insurance / appointment count (clinic-specific).
      contextBlock = `<${recordTag}>
name: ${ctx.patient.firstName} ${ctx.patient.lastName}
${ctx.patient.email ? `email: ${ctx.patient.email}\n` : ''}${ctx.patient.phone ? `phone: ${ctx.patient.phone}\n` : ''}${ctx.patient.notes ? `notes: ${ctx.patient.notes}` : ''}
</${recordTag}>`
    } else {
      contextBlock = `<${recordTag}>
name: ${ctx.patient.firstName} ${ctx.patient.lastName}
${ctx.patient.dateOfBirth ? `date_of_birth: ${ctx.patient.dateOfBirth}\n` : ''}${ctx.patient.phone ? `phone: ${ctx.patient.phone}\n` : ''}${ctx.patient.insuranceProvider ? `insurance: ${ctx.patient.insuranceProvider}\n` : ''}total_visits: ${ctx.appointmentCount}
${ctx.nextAppointment ? `next_appointment: ${ctx.nextAppointment.startTime.toISOString()} (${ctx.nextAppointment.type}, ${ctx.nextAppointment.status})` : 'next_appointment: none scheduled'}
${ctx.lastAppointment && new Date(ctx.lastAppointment.startTime) < new Date() ? `last_visit: ${ctx.lastAppointment.startTime.toISOString()} (${ctx.lastAppointment.type})` : 'last_visit: none on record'}
${ctx.patient.notes ? `notes: ${ctx.patient.notes}` : ''}
</${recordTag}>`
    }
  } else {
    const noun = isPlatform ? 'client' : 'patient'
    contextBlock = `<${recordTag}>This sender is NOT in our ${noun} records.</${recordTag}>`
  }

  const userText = `${contextBlock}

<incoming_email>
From: ${args.fromName ? `${args.fromName} <${args.fromEmail}>` : args.fromEmail}
Subject: ${args.originalSubject ?? '(no subject)'}

${args.originalBody.slice(0, 6000)}
</incoming_email>

Draft a reply now. Output only the email body — no preamble, no explanation.`

  try {
    // Stream internally to avoid SDK HTTP timeouts on slow generations;
    // collect into a single string before returning. Adaptive thinking
    // lets the model dial up reasoning when the reply is non-trivial.
    const out = await runClaudeText({
      model: 'sonnet',
      maxTokens: 4000,
      thinking: true,
      system: isPlatform ? REPLY_SYSTEM_PLATFORM : REPLY_SYSTEM_CLINIC,
      messages: [{ role: 'user', content: userText }],
    })
    return out ? out.trim() : null
  } catch (err) {
    console.warn('[ai.draft] failed:', (err as Error).message)
    return null
  }
}

// ============================================================
// Batched classification (parallel with bounded concurrency)
// ============================================================

/**
 * Classify a batch of messages in parallel. Bounded concurrency so a
 * 200-message backfill doesn't burst the Haiku rate limit. Returns a map
 * of messageId → { category, intent } for ones we successfully classified.
 */
export async function classifyBatch(
  messages: Array<ClassifyInput & { id: string }>,
  concurrency = 8,
): Promise<Map<string, EmailClassification>> {
  const result = new Map<string, EmailClassification>()
  let cursor = 0
  async function worker() {
    while (cursor < messages.length) {
      const i = cursor++
      const msg = messages[i]
      const classification = await classifyMessage(msg)
      if (classification) result.set(msg.id, classification)
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, messages.length) }, worker))
  return result
}

// Backward-compat wrapper (older callers expected just an intent).
export async function classifyIntent(args: ClassifyInput): Promise<EmailIntent | null> {
  const result = await classifyMessage(args)
  return result?.intent ?? null
}
